/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MapRouteImport } from './routes/map'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as StoreIdRouteImport } from './routes/store.$id'
import { Route as OrdersNativeReturnRouteImport } from './routes/orders.native-return'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as OfferIdRouteImport } from './routes/offer.$id'
import { Route as AuthNativeReturnRouteImport } from './routes/auth.native-return'
import { Route as AuthenticatedPartnerApplyRouteImport } from './routes/_authenticated/partner-apply'
import { Route as AuthenticatedPartnerRouteImport } from './routes/_authenticated/partner'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPartnerIndexRouteImport } from './routes/_authenticated/partner.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedPartnerStoreRouteImport } from './routes/_authenticated/partner.store'
import { Route as AuthenticatedPartnerStatsRouteImport } from './routes/_authenticated/partner.stats'
import { Route as AuthenticatedPartnerScanRouteImport } from './routes/_authenticated/partner.scan'
import { Route as AuthenticatedPartnerQuickRouteImport } from './routes/_authenticated/partner.quick'
import { Route as AuthenticatedPartnerProfileRouteImport } from './routes/_authenticated/partner.profile'
import { Route as AuthenticatedPartnerOrdersRouteImport } from './routes/_authenticated/partner.orders'
import { Route as AuthenticatedPartnerOffersRouteImport } from './routes/_authenticated/partner.offers'
import { Route as AuthenticatedPartnerNewRouteImport } from './routes/_authenticated/partner.new'
import { Route as AuthenticatedPartnerInsightsRouteImport } from './routes/_authenticated/partner.insights'
import { Route as AuthenticatedPartnerDeliveryRouteImport } from './routes/_authenticated/partner.delivery'
import { Route as AuthenticatedPartnerBalanceRouteImport } from './routes/_authenticated/partner.balance'
import { Route as AuthenticatedPartnerAiRouteImport } from './routes/_authenticated/partner.ai'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminStatsRouteImport } from './routes/_authenticated/admin.stats'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin.partners'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminOffersRouteImport } from './routes/_authenticated/admin.offers'
import { Route as ApiPublicPaymentsBogCallbackRouteImport } from './routes/api/public/payments/bog-callback'
import { Route as ApiPublicDeliveryWoltRouteImport } from './routes/api/public/delivery/wolt'
import { Route as ApiPublicDeliveryGlovoRouteImport } from './routes/api/public/delivery/glovo'
import { Route as ApiPublicDeliveryBoltRouteImport } from './routes/api/public/delivery/bolt'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIdRoute = StoreIdRouteImport.update({
  id: '/store/$id',
  path: '/store/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNativeReturnRoute = OrdersNativeReturnRouteImport.update({
  id: '/orders/native-return',
  path: '/orders/native-return',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferIdRoute = OfferIdRouteImport.update({
  id: '/offer/$id',
  path: '/offer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNativeReturnRoute = AuthNativeReturnRouteImport.update({
  id: '/native-return',
  path: '/native-return',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedPartnerApplyRoute =
  AuthenticatedPartnerApplyRouteImport.update({
    id: '/partner-apply',
    path: '/partner-apply',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartnerRoute = AuthenticatedPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnerIndexRoute =
  AuthenticatedPartnerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPartnerStoreRoute =
  AuthenticatedPartnerStoreRouteImport.update({
    id: '/store',
    path: '/store',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerStatsRoute =
  AuthenticatedPartnerStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerScanRoute =
  AuthenticatedPartnerScanRouteImport.update({
    id: '/scan',
    path: '/scan',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerQuickRoute =
  AuthenticatedPartnerQuickRouteImport.update({
    id: '/quick',
    path: '/quick',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerProfileRoute =
  AuthenticatedPartnerProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerOrdersRoute =
  AuthenticatedPartnerOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerOffersRoute =
  AuthenticatedPartnerOffersRouteImport.update({
    id: '/offers',
    path: '/offers',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerNewRoute = AuthenticatedPartnerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedPartnerRoute,
} as any)
const AuthenticatedPartnerInsightsRoute =
  AuthenticatedPartnerInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerDeliveryRoute =
  AuthenticatedPartnerDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerBalanceRoute =
  AuthenticatedPartnerBalanceRouteImport.update({
    id: '/balance',
    path: '/balance',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerAiRoute = AuthenticatedPartnerAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedPartnerRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStatsRoute = AuthenticatedAdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOffersRoute =
  AuthenticatedAdminOffersRouteImport.update({
    id: '/offers',
    path: '/offers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicPaymentsBogCallbackRoute =
  ApiPublicPaymentsBogCallbackRouteImport.update({
    id: '/api/public/payments/bog-callback',
    path: '/api/public/payments/bog-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDeliveryWoltRoute = ApiPublicDeliveryWoltRouteImport.update({
  id: '/api/public/delivery/wolt',
  path: '/api/public/delivery/wolt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeliveryGlovoRoute = ApiPublicDeliveryGlovoRouteImport.update({
  id: '/api/public/delivery/glovo',
  path: '/api/public/delivery/glovo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeliveryBoltRoute = ApiPublicDeliveryBoltRouteImport.update({
  id: '/api/public/delivery/bolt',
  path: '/api/public/delivery/bolt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/partner': typeof AuthenticatedPartnerRouteWithChildren
  '/partner-apply': typeof AuthenticatedPartnerApplyRoute
  '/auth/native-return': typeof AuthNativeReturnRoute
  '/offer/$id': typeof OfferIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/native-return': typeof OrdersNativeReturnRoute
  '/store/$id': typeof StoreIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/partner/ai': typeof AuthenticatedPartnerAiRoute
  '/partner/balance': typeof AuthenticatedPartnerBalanceRoute
  '/partner/delivery': typeof AuthenticatedPartnerDeliveryRoute
  '/partner/insights': typeof AuthenticatedPartnerInsightsRoute
  '/partner/new': typeof AuthenticatedPartnerNewRoute
  '/partner/offers': typeof AuthenticatedPartnerOffersRoute
  '/partner/orders': typeof AuthenticatedPartnerOrdersRoute
  '/partner/profile': typeof AuthenticatedPartnerProfileRoute
  '/partner/quick': typeof AuthenticatedPartnerQuickRoute
  '/partner/scan': typeof AuthenticatedPartnerScanRoute
  '/partner/stats': typeof AuthenticatedPartnerStatsRoute
  '/partner/store': typeof AuthenticatedPartnerStoreRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/partner/': typeof AuthenticatedPartnerIndexRoute
  '/api/public/delivery/bolt': typeof ApiPublicDeliveryBoltRoute
  '/api/public/delivery/glovo': typeof ApiPublicDeliveryGlovoRoute
  '/api/public/delivery/wolt': typeof ApiPublicDeliveryWoltRoute
  '/api/public/payments/bog-callback': typeof ApiPublicPaymentsBogCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/partner-apply': typeof AuthenticatedPartnerApplyRoute
  '/auth/native-return': typeof AuthNativeReturnRoute
  '/offer/$id': typeof OfferIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/native-return': typeof OrdersNativeReturnRoute
  '/store/$id': typeof StoreIdRoute
  '/orders': typeof OrdersIndexRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/partner/ai': typeof AuthenticatedPartnerAiRoute
  '/partner/balance': typeof AuthenticatedPartnerBalanceRoute
  '/partner/delivery': typeof AuthenticatedPartnerDeliveryRoute
  '/partner/insights': typeof AuthenticatedPartnerInsightsRoute
  '/partner/new': typeof AuthenticatedPartnerNewRoute
  '/partner/offers': typeof AuthenticatedPartnerOffersRoute
  '/partner/orders': typeof AuthenticatedPartnerOrdersRoute
  '/partner/profile': typeof AuthenticatedPartnerProfileRoute
  '/partner/quick': typeof AuthenticatedPartnerQuickRoute
  '/partner/scan': typeof AuthenticatedPartnerScanRoute
  '/partner/stats': typeof AuthenticatedPartnerStatsRoute
  '/partner/store': typeof AuthenticatedPartnerStoreRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/partner': typeof AuthenticatedPartnerIndexRoute
  '/api/public/delivery/bolt': typeof ApiPublicDeliveryBoltRoute
  '/api/public/delivery/glovo': typeof ApiPublicDeliveryGlovoRoute
  '/api/public/delivery/wolt': typeof ApiPublicDeliveryWoltRoute
  '/api/public/payments/bog-callback': typeof ApiPublicPaymentsBogCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/partner': typeof AuthenticatedPartnerRouteWithChildren
  '/_authenticated/partner-apply': typeof AuthenticatedPartnerApplyRoute
  '/auth/native-return': typeof AuthNativeReturnRoute
  '/offer/$id': typeof OfferIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/native-return': typeof OrdersNativeReturnRoute
  '/store/$id': typeof StoreIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/_authenticated/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/partner/ai': typeof AuthenticatedPartnerAiRoute
  '/_authenticated/partner/balance': typeof AuthenticatedPartnerBalanceRoute
  '/_authenticated/partner/delivery': typeof AuthenticatedPartnerDeliveryRoute
  '/_authenticated/partner/insights': typeof AuthenticatedPartnerInsightsRoute
  '/_authenticated/partner/new': typeof AuthenticatedPartnerNewRoute
  '/_authenticated/partner/offers': typeof AuthenticatedPartnerOffersRoute
  '/_authenticated/partner/orders': typeof AuthenticatedPartnerOrdersRoute
  '/_authenticated/partner/profile': typeof AuthenticatedPartnerProfileRoute
  '/_authenticated/partner/quick': typeof AuthenticatedPartnerQuickRoute
  '/_authenticated/partner/scan': typeof AuthenticatedPartnerScanRoute
  '/_authenticated/partner/stats': typeof AuthenticatedPartnerStatsRoute
  '/_authenticated/partner/store': typeof AuthenticatedPartnerStoreRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/partner/': typeof AuthenticatedPartnerIndexRoute
  '/api/public/delivery/bolt': typeof ApiPublicDeliveryBoltRoute
  '/api/public/delivery/glovo': typeof ApiPublicDeliveryGlovoRoute
  '/api/public/delivery/wolt': typeof ApiPublicDeliveryWoltRoute
  '/api/public/payments/bog-callback': typeof ApiPublicPaymentsBogCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/auth'
    | '/favorites'
    | '/map'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/partner'
    | '/partner-apply'
    | '/auth/native-return'
    | '/offer/$id'
    | '/orders/$id'
    | '/orders/native-return'
    | '/store/$id'
    | '/orders/'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/users'
    | '/partner/ai'
    | '/partner/balance'
    | '/partner/delivery'
    | '/partner/insights'
    | '/partner/new'
    | '/partner/offers'
    | '/partner/orders'
    | '/partner/profile'
    | '/partner/quick'
    | '/partner/scan'
    | '/partner/stats'
    | '/partner/store'
    | '/admin/'
    | '/partner/'
    | '/api/public/delivery/bolt'
    | '/api/public/delivery/glovo'
    | '/api/public/delivery/wolt'
    | '/api/public/payments/bog-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/auth'
    | '/favorites'
    | '/map'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/partner-apply'
    | '/auth/native-return'
    | '/offer/$id'
    | '/orders/$id'
    | '/orders/native-return'
    | '/store/$id'
    | '/orders'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/users'
    | '/partner/ai'
    | '/partner/balance'
    | '/partner/delivery'
    | '/partner/insights'
    | '/partner/new'
    | '/partner/offers'
    | '/partner/orders'
    | '/partner/profile'
    | '/partner/quick'
    | '/partner/scan'
    | '/partner/stats'
    | '/partner/store'
    | '/admin'
    | '/partner'
    | '/api/public/delivery/bolt'
    | '/api/public/delivery/glovo'
    | '/api/public/delivery/wolt'
    | '/api/public/payments/bog-callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/analytics'
    | '/auth'
    | '/favorites'
    | '/map'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/partner'
    | '/_authenticated/partner-apply'
    | '/auth/native-return'
    | '/offer/$id'
    | '/orders/$id'
    | '/orders/native-return'
    | '/store/$id'
    | '/orders/'
    | '/_authenticated/admin/offers'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/stats'
    | '/_authenticated/admin/users'
    | '/_authenticated/partner/ai'
    | '/_authenticated/partner/balance'
    | '/_authenticated/partner/delivery'
    | '/_authenticated/partner/insights'
    | '/_authenticated/partner/new'
    | '/_authenticated/partner/offers'
    | '/_authenticated/partner/orders'
    | '/_authenticated/partner/profile'
    | '/_authenticated/partner/quick'
    | '/_authenticated/partner/scan'
    | '/_authenticated/partner/stats'
    | '/_authenticated/partner/store'
    | '/_authenticated/admin/'
    | '/_authenticated/partner/'
    | '/api/public/delivery/bolt'
    | '/api/public/delivery/glovo'
    | '/api/public/delivery/wolt'
    | '/api/public/payments/bog-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  OfferIdRoute: typeof OfferIdRoute
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersNativeReturnRoute: typeof OrdersNativeReturnRoute
  StoreIdRoute: typeof StoreIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ApiPublicDeliveryBoltRoute: typeof ApiPublicDeliveryBoltRoute
  ApiPublicDeliveryGlovoRoute: typeof ApiPublicDeliveryGlovoRoute
  ApiPublicDeliveryWoltRoute: typeof ApiPublicDeliveryWoltRoute
  ApiPublicPaymentsBogCallbackRoute: typeof ApiPublicPaymentsBogCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$id': {
      id: '/store/$id'
      path: '/store/$id'
      fullPath: '/store/$id'
      preLoaderRoute: typeof StoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/native-return': {
      id: '/orders/native-return'
      path: '/orders/native-return'
      fullPath: '/orders/native-return'
      preLoaderRoute: typeof OrdersNativeReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/$id': {
      id: '/offer/$id'
      path: '/offer/$id'
      fullPath: '/offer/$id'
      preLoaderRoute: typeof OfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/native-return': {
      id: '/auth/native-return'
      path: '/native-return'
      fullPath: '/auth/native-return'
      preLoaderRoute: typeof AuthNativeReturnRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/partner-apply': {
      id: '/_authenticated/partner-apply'
      path: '/partner-apply'
      fullPath: '/partner-apply'
      preLoaderRoute: typeof AuthenticatedPartnerApplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner': {
      id: '/_authenticated/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AuthenticatedPartnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner/': {
      id: '/_authenticated/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof AuthenticatedPartnerIndexRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/partner/store': {
      id: '/_authenticated/partner/store'
      path: '/store'
      fullPath: '/partner/store'
      preLoaderRoute: typeof AuthenticatedPartnerStoreRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/stats': {
      id: '/_authenticated/partner/stats'
      path: '/stats'
      fullPath: '/partner/stats'
      preLoaderRoute: typeof AuthenticatedPartnerStatsRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/scan': {
      id: '/_authenticated/partner/scan'
      path: '/scan'
      fullPath: '/partner/scan'
      preLoaderRoute: typeof AuthenticatedPartnerScanRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/quick': {
      id: '/_authenticated/partner/quick'
      path: '/quick'
      fullPath: '/partner/quick'
      preLoaderRoute: typeof AuthenticatedPartnerQuickRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/profile': {
      id: '/_authenticated/partner/profile'
      path: '/profile'
      fullPath: '/partner/profile'
      preLoaderRoute: typeof AuthenticatedPartnerProfileRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/orders': {
      id: '/_authenticated/partner/orders'
      path: '/orders'
      fullPath: '/partner/orders'
      preLoaderRoute: typeof AuthenticatedPartnerOrdersRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/offers': {
      id: '/_authenticated/partner/offers'
      path: '/offers'
      fullPath: '/partner/offers'
      preLoaderRoute: typeof AuthenticatedPartnerOffersRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/new': {
      id: '/_authenticated/partner/new'
      path: '/new'
      fullPath: '/partner/new'
      preLoaderRoute: typeof AuthenticatedPartnerNewRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/insights': {
      id: '/_authenticated/partner/insights'
      path: '/insights'
      fullPath: '/partner/insights'
      preLoaderRoute: typeof AuthenticatedPartnerInsightsRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/delivery': {
      id: '/_authenticated/partner/delivery'
      path: '/delivery'
      fullPath: '/partner/delivery'
      preLoaderRoute: typeof AuthenticatedPartnerDeliveryRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/balance': {
      id: '/_authenticated/partner/balance'
      path: '/balance'
      fullPath: '/partner/balance'
      preLoaderRoute: typeof AuthenticatedPartnerBalanceRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/ai': {
      id: '/_authenticated/partner/ai'
      path: '/ai'
      fullPath: '/partner/ai'
      preLoaderRoute: typeof AuthenticatedPartnerAiRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stats': {
      id: '/_authenticated/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AuthenticatedAdminStatsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/offers': {
      id: '/_authenticated/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AuthenticatedAdminOffersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/payments/bog-callback': {
      id: '/api/public/payments/bog-callback'
      path: '/api/public/payments/bog-callback'
      fullPath: '/api/public/payments/bog-callback'
      preLoaderRoute: typeof ApiPublicPaymentsBogCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/delivery/wolt': {
      id: '/api/public/delivery/wolt'
      path: '/api/public/delivery/wolt'
      fullPath: '/api/public/delivery/wolt'
      preLoaderRoute: typeof ApiPublicDeliveryWoltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/delivery/glovo': {
      id: '/api/public/delivery/glovo'
      path: '/api/public/delivery/glovo'
      fullPath: '/api/public/delivery/glovo'
      preLoaderRoute: typeof ApiPublicDeliveryGlovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/delivery/bolt': {
      id: '/api/public/delivery/bolt'
      path: '/api/public/delivery/bolt'
      fullPath: '/api/public/delivery/bolt'
      preLoaderRoute: typeof ApiPublicDeliveryBoltRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminOffersRoute: typeof AuthenticatedAdminOffersRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStatsRoute: typeof AuthenticatedAdminStatsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminOffersRoute: AuthenticatedAdminOffersRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStatsRoute: AuthenticatedAdminStatsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPartnerRouteChildren {
  AuthenticatedPartnerAiRoute: typeof AuthenticatedPartnerAiRoute
  AuthenticatedPartnerBalanceRoute: typeof AuthenticatedPartnerBalanceRoute
  AuthenticatedPartnerDeliveryRoute: typeof AuthenticatedPartnerDeliveryRoute
  AuthenticatedPartnerInsightsRoute: typeof AuthenticatedPartnerInsightsRoute
  AuthenticatedPartnerNewRoute: typeof AuthenticatedPartnerNewRoute
  AuthenticatedPartnerOffersRoute: typeof AuthenticatedPartnerOffersRoute
  AuthenticatedPartnerOrdersRoute: typeof AuthenticatedPartnerOrdersRoute
  AuthenticatedPartnerProfileRoute: typeof AuthenticatedPartnerProfileRoute
  AuthenticatedPartnerQuickRoute: typeof AuthenticatedPartnerQuickRoute
  AuthenticatedPartnerScanRoute: typeof AuthenticatedPartnerScanRoute
  AuthenticatedPartnerStatsRoute: typeof AuthenticatedPartnerStatsRoute
  AuthenticatedPartnerStoreRoute: typeof AuthenticatedPartnerStoreRoute
  AuthenticatedPartnerIndexRoute: typeof AuthenticatedPartnerIndexRoute
}

const AuthenticatedPartnerRouteChildren: AuthenticatedPartnerRouteChildren = {
  AuthenticatedPartnerAiRoute: AuthenticatedPartnerAiRoute,
  AuthenticatedPartnerBalanceRoute: AuthenticatedPartnerBalanceRoute,
  AuthenticatedPartnerDeliveryRoute: AuthenticatedPartnerDeliveryRoute,
  AuthenticatedPartnerInsightsRoute: AuthenticatedPartnerInsightsRoute,
  AuthenticatedPartnerNewRoute: AuthenticatedPartnerNewRoute,
  AuthenticatedPartnerOffersRoute: AuthenticatedPartnerOffersRoute,
  AuthenticatedPartnerOrdersRoute: AuthenticatedPartnerOrdersRoute,
  AuthenticatedPartnerProfileRoute: AuthenticatedPartnerProfileRoute,
  AuthenticatedPartnerQuickRoute: AuthenticatedPartnerQuickRoute,
  AuthenticatedPartnerScanRoute: AuthenticatedPartnerScanRoute,
  AuthenticatedPartnerStatsRoute: AuthenticatedPartnerStatsRoute,
  AuthenticatedPartnerStoreRoute: AuthenticatedPartnerStoreRoute,
  AuthenticatedPartnerIndexRoute: AuthenticatedPartnerIndexRoute,
}

const AuthenticatedPartnerRouteWithChildren =
  AuthenticatedPartnerRoute._addFileChildren(AuthenticatedPartnerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPartnerRoute: typeof AuthenticatedPartnerRouteWithChildren
  AuthenticatedPartnerApplyRoute: typeof AuthenticatedPartnerApplyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPartnerRoute: AuthenticatedPartnerRouteWithChildren,
  AuthenticatedPartnerApplyRoute: AuthenticatedPartnerApplyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthNativeReturnRoute: typeof AuthNativeReturnRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthNativeReturnRoute: AuthNativeReturnRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  OfferIdRoute: OfferIdRoute,
  OrdersIdRoute: OrdersIdRoute,
  OrdersNativeReturnRoute: OrdersNativeReturnRoute,
  StoreIdRoute: StoreIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ApiPublicDeliveryBoltRoute: ApiPublicDeliveryBoltRoute,
  ApiPublicDeliveryGlovoRoute: ApiPublicDeliveryGlovoRoute,
  ApiPublicDeliveryWoltRoute: ApiPublicDeliveryWoltRoute,
  ApiPublicPaymentsBogCallbackRoute: ApiPublicPaymentsBogCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
